In [2]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [3]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4 , 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [4]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [5]:
np.random.rand()
np.random.rand(30, 4)

array([[0.11385782, 0.29563183, 0.23656102, 0.75013088],
       [0.52664971, 0.88917103, 0.78762927, 0.75831196],
       [0.45514941, 0.53995621, 0.62270508, 0.90739117],
       [0.28188614, 0.62612762, 0.40282718, 0.8662164 ],
       [0.96786902, 0.39087997, 0.52444018, 0.77008053],
       [0.73188221, 0.5717787 , 0.37392427, 0.45925055],
       [0.44167389, 0.52403188, 0.87782976, 0.39266575],
       [0.17430481, 0.4040368 , 0.70179552, 0.78795063],
       [0.44713116, 0.75392558, 0.07018642, 0.22457694],
       [0.94071183, 0.36254696, 0.88747696, 0.29932174],
       [0.90127634, 0.01042403, 0.92944652, 0.33561499],
       [0.59178173, 0.84860166, 0.14047238, 0.47666977],
       [0.45510512, 0.83617732, 0.02022105, 0.64218654],
       [0.73895267, 0.51659195, 0.74965107, 0.7328389 ],
       [0.22827986, 0.39570506, 0.77536397, 0.65071914],
       [0.66586262, 0.86891852, 0.54356348, 0.45762758],
       [0.40456848, 0.74910744, 0.03882401, 0.71751529],
       [0.55494139, 0.83681052,

In [6]:
scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 84,  65,  61,  97,  65],
       [ 61,  98,  79,  91,  67],
       [ 60,  92,  53,  91,  67],
       [ 52,  63,  84,  60,  98],
       [ 50,  94,  95,  66,  64],
       [ 99,  56,  56,  94,  56],
       [ 73,  95,  95,  87, 100],
       [ 88,  87,  80,  58,  56],
       [ 79,  98,  99,  56,  74],
       [ 87,  81,  81,  79,  87],
       [ 76,  53,  99,  72,  74],
       [ 92,  60,  55,  71,  85],
       [ 57,  91,  89,  76,  70],
       [ 86,  68,  52,  79,  50],
       [ 61,  78,  61,  79,  81],
       [ 73,  77,  94,  62,  51],
       [ 67,  94,  66, 100,  79],
       [ 67,  60,  92,  62,  61],
       [ 52,  59,  54,  81,  56],
       [ 54,  64,  68,  92,  98],
       [ 67,  57,  58,  57,  77],
       [ 54,  62,  96,  91,  91],
       [ 89,  99,  70,  73,  72],
       [ 50,  52,  80,  94,  93],
       [ 57,  99,  99,  89,  81],
       [ 65,  98,  73,  58,  64],
       [ 70,  95,  82,  69,  56],
       [ 80,  65,  53,  50,  91],
       [ 70,  74,  89,  82,  97],
       [ 89,  