In [2]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:]#最後5個

array([50, 60, 70, 80, 90])

In [7]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 67,  62,  76,  64,  93],
       [ 58,  58,  85,  53,  79],
       [ 87,  70,  99,  84,  55],
       [ 70,  92,  74,  62,  52],
       [ 91,  81,  58, 100,  79],
       [ 71,  67,  68,  62,  93],
       [ 94,  86,  86,  61,  66],
       [ 82, 100,  90,  80,  58],
       [ 54,  70,  80,  61,  78],
       [ 55,  60,  53,  68,  74],
       [ 66,  74,  73,  72,  80],
       [ 66,  65,  83,  80,  73],
       [ 73,  93,  86,  98,  85],
       [ 93,  95,  73,  96,  50],
       [ 65,  53,  65,  86,  97],
       [ 99,  53,  88,  97,  54],
       [ 66,  78,  52,  86,  99],
       [ 62,  56,  57,  54,  79],
       [ 61,  50,  56,  77,  54],
       [ 98,  87,  79,  68,  84],
       [ 72,  78,  87,  59, 100],
       [ 98,  74,  77,  91,  96],
       [ 56,  86,  51,  54,  95],
       [ 83,  67,  81,  78,  87],
       [ 91,  70,  68,  55,  75],
       [ 63,  96,  69,  79,  96],
       [ 72,  51,  81,  55,  68],
       [ 79, 100,  63,  67,  92],
       [ 70,  87,  82,  84,  95],
       [ 95,  

In [13]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[67, 62, 76, 64, 93]], dtype=int32)

In [8]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([76, 85, 99, 74, 58, 68, 86, 90, 80, 53, 73, 83, 86, 73, 65, 88, 52,
       57, 56, 79, 87, 77, 51, 81, 68, 69, 81, 63, 82, 82, 78, 84, 95, 89,
       56, 57, 77, 53, 78, 94, 56, 97, 65, 51, 58, 52, 84, 77, 96, 63],
      dtype=int32)

In [9]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[67, 62, 76],
       [58, 58, 85],
       [87, 70, 99],
       [70, 92, 74],
       [91, 81, 58]], dtype=int32)

In [10]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([76, 85, 99, 74, 58, 68, 86, 90, 80, 53, 73, 83, 86, 73, 65, 88, 52,
       57, 56, 79, 87, 77, 51, 81, 68, 69, 81, 63, 82, 82, 78, 84, 95, 89,
       56, 57, 77, 53, 78, 94, 56, 97, 65, 51, 58, 52, 84, 77, 96, 63],
      dtype=int32)

In [11]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([362, 333, 395, 350, 409, 361, 393, 410, 343, 310, 365, 367, 435,
       407, 366, 391, 381, 308, 298, 416, 396, 436, 342, 396, 359, 403,
       327, 401, 418, 410, 412, 341, 381, 398, 299, 364, 389, 333, 367,
       367, 317, 434, 294, 366, 360, 365, 366, 370, 406, 391], dtype=int32)

In [12]:
total / 5

array([72.4, 66.6, 79. , 70. , 81.8, 72.2, 78.6, 82. , 68.6, 62. , 73. ,
       73.4, 87. , 81.4, 73.2, 78.2, 76.2, 61.6, 59.6, 83.2, 79.2, 87.2,
       68.4, 79.2, 71.8, 80.6, 65.4, 80.2, 83.6, 82. , 82.4, 68.2, 76.2,
       79.6, 59.8, 72.8, 77.8, 66.6, 73.4, 73.4, 63.4, 86.8, 58.8, 73.2,
       72. , 73. , 73.2, 74. , 81.2, 78.2])

In [14]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([72.4, 66.6, 79. , 70. , 81.8, 72.2, 78.6, 82. , 68.6, 62. , 73. ,
       73.4, 87. , 81.4, 73.2, 78.2, 76.2, 61.6, 59.6, 83.2, 79.2, 87.2,
       68.4, 79.2, 71.8, 80.6, 65.4, 80.2, 83.6, 82. , 82.4, 68.2, 76.2,
       79.6, 59.8, 72.8, 77.8, 66.6, 73.4, 73.4, 63.4, 86.8, 58.8, 73.2,
       72. , 73. , 73.2, 74. , 81.2, 78.2])

In [15]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([72.4, 66.6, 79. , 70. , 81.8, 72.2, 78.6, 82. , 68.6, 62. , 73. ,
       73.4, 87. , 81.4, 73.2, 78.2, 76.2, 61.6, 59.6, 83.2, 79.2, 87.2,
       68.4, 79.2, 71.8, 80.6, 65.4, 80.2, 83.6, 82. , 82.4, 68.2, 76.2,
       79.6, 59.8, 72.8, 77.8, 66.6, 73.4, 73.4, 63.4, 86.8, 58.8, 73.2,
       72. , 73. , 73.2, 74. , 81.2, 78.2])